### PR TITLE
Custom execFile options

### PR DESCRIPTION
**Pull request by amytych**
I found out that in some cases even 500KB was not enough, so I added possibility to pass exec options. This allows custom maxBuffer as well as setting any other options for execFile.

### CODE REVIEW

**Comment by lillem4n** [comment]
I very much like this flexibility and it is a good pull request with test and all. Thanks for that!

However, I'd love to see it as part of the standard options-stack, kind of like:

```javascript
urltopdf({'url': 'http://www.fsf.org/', 'execOptions': {'maxBuffer': 500 * 1024}}, function(err, pdfBuffer) {
```

The reasons I have for this is, I think:

* Easier validating of parameters (only url/options and callback)
* More extendable with even more options in the future

I'm very open to why having execOptions as a separate parameter is a better solution.

**Comment by lillem4n** [comment]
Oh, also it will be explicit in the actuall call to urltopdf() that it is in fact execOptions being sent in.

**Comment by amytych** [comment]
Yes, you're totally right, I was looking at the execFile signature where the options are separate and went that route. I'll make the adjustments you suggested.

**Comment by lillem4n** [comment]
Beautiful! \o/ Thanks a lot! Its merged now and I've pushed a new version to npm

**Pull request merged**
